TUNING.ARMORGRASS = TUNING.ARMORGRASS * GetModConfigData("ARMORGRASS")
TUNING.ARMORWOOD = TUNING.ARMORWOOD * GetModConfigData("ARMORWOOD")
TUNING.ARMORMARBLE = TUNING.ARMORMARBLE * GetModConfigData("ARMORMARBLE")
TUNING.ARMORMARBLE_SLOW = GetModConfigData("ARMORMARBLE_SLOW")
TUNING.ARMORSNURTLESHELL = TUNING.ARMORSNURTLESHELL * GetModConfigData("ARMORSNURTLESHELL")
TUNING.ARMORRUINS = TUNING.ARMORRUINS * GetModConfigData("ARMORRUINS")
TUNING.ARMOR_SANITY = TUNING.ARMOR_SANITY * GetModConfigData("ARMOR_SANITY")

TUNING.ARMOR_FOOTBALLHAT = TUNING.ARMOR_FOOTBALLHAT * GetModConfigData("ARMOR_FOOTBALLHAT")
TUNING.ARMOR_BEEHAT = TUNING.ARMOR_BEEHAT * GetModConfigData("ARMOR_BEEHAT")
TUNING.ARMOR_SLURTLEHAT = TUNING.ARMOR_SLURTLEHAT * GetModConfigData("ARMOR_SLURTLEHAT")
TUNING.ARMOR_RUINSHAT = TUNING.ARMOR_RUINSHAT * GetModConfigData("ARMOR_RUINSHAT")

--RoG
if not ARMOR_WATHGRITHRHAT == nil then
	TUNING.ARMORDRAGONFLY = TUNING.ARMORDRAGONFLY * GetModConfigData("ARMORDRAGONFLY")
	TUNING.ARMOR_WATHGRITHRHAT = TUNING.ARMOR_WATHGRITHRHAT * GetModConfigData("ARMOR_WATHGRITHRHAT")
end

--SW
if not TUNING.ARMORSEASHELL == nil then
	TUNING.ARMORSEASHELL = TUNING.ARMORSEASHELL * GetModConfigData("ARMORSEASHELL")
	TUNING.ARMORLIMESTONE = TUNING.ARMORLIMESTONE * GetModConfigData("ARMORLIMESTONE")
	TUNING.ARMORDRAGONFLY = TUNING.ARMORDRAGONFLY * GetModConfigData("ARMORABSIDIAN")
	TUNING.ARMORCACTUS = TUNING.ARMORCACTUS * GetModConfigData("ARMORCACTUS")
	TUNING.ARMOR_OXHAT = TUNING.ARMOR_OXHAT * GetModConfigData("ARMOR_OXHAT")
end