GLOBAL.TUNING.ARMORGRASS = GLOBAL.TUNING.ARMORGRASS * GetModConfigData("ARMORGRASS")
GLOBAL.TUNING.ARMORWOOD = GLOBAL.TUNING.ARMORWOOD * GetModConfigData("ARMORWOOD")
GLOBAL.TUNING.ARMORMARBLE = GLOBAL.TUNING.ARMORMARBLE * GetModConfigData("ARMORMARBLE")
GLOBAL.TUNING.ARMORMARBLE_SLOW = GLOBAL.TUNING.ARMORMARBLE_SLOW + GetModConfigData("ARMORMARBLE_SLOW")

GLOBAL.TUNING.ARMORSNURTLESHELL = GLOBAL.TUNING.ARMORSNURTLESHELL * GetModConfigData("ARMORSNURTLESHELL")
GLOBAL.TUNING.ARMORRUINS = GLOBAL.TUNING.ARMORRUINS * GetModConfigData("ARMORRUINS")
GLOBAL.TUNING.ARMOR_SANITY = GLOBAL.TUNING.ARMOR_SANITY * GetModConfigData("ARMOR_SANITY")

GLOBAL.TUNING.ARMOR_FOOTBALLHAT = GLOBAL.TUNING.ARMOR_FOOTBALLHAT * GetModConfigData("ARMOR_FOOTBALLHAT")
GLOBAL.TUNING.ARMOR_BEEHAT = GLOBAL.TUNING.ARMOR_BEEHAT * GetModConfigData("ARMOR_BEEHAT")
GLOBAL.TUNING.ARMOR_SLURTLEHAT = GLOBAL.TUNING.ARMOR_SLURTLEHAT * GetModConfigData("ARMOR_SLURTLEHAT")
GLOBAL.TUNING.ARMOR_RUINSHAT = GLOBAL.TUNING.ARMOR_RUINSHAT * GetModConfigData("ARMOR_RUINSHAT")

--RoG
if not ARMOR_WATHGRITHRHAT == nil then
	GLOBAL.TUNING.ARMORDRAGONFLY = GLOBAL.TUNING.ARMORDRAGONFLY * GetModConfigData("ARMORDRAGONFLY")
	GLOBAL.TUNING.ARMOR_WATHGRITHRHAT = GLOBAL.TUNING.ARMOR_WATHGRITHRHAT * GetModConfigData("ARMOR_WATHGRITHRHAT")
end

--SW
if not GLOBAL.TUNING.ARMORSEASHELL == nil then
	GLOBAL.TUNING.ARMORSEASHELL = GLOBAL.TUNING.ARMORSEASHELL * GetModConfigData("ARMORSEASHELL")
	GLOBAL.TUNING.ARMORLIMESTONE = GLOBAL.TUNING.ARMORLIMESTONE * GetModConfigData("ARMORLIMESTONE")
	GLOBAL.TUNING.ARMORDRAGONFLY = GLOBAL.TUNING.ARMORDRAGONFLY * GetModConfigData("ARMORABSIDIAN")
	GLOBAL.TUNING.ARMORCACTUS = GLOBAL.TUNING.ARMORCACTUS * GetModConfigData("ARMORCACTUS")
	GLOBAL.TUNING.ARMOR_OXHAT = GLOBAL.TUNING.ARMOR_OXHAT * GetModConfigData("ARMOR_OXHAT")
end