-- Tuning
GLOBAL.TUNING.MUSHSPORE_PERISH_TIME = GLOBAL.TUNING.SEG_TIME * 3
GLOBAL.TUNING.MUSHSPORE_MAX_DENSITY = 10
GLOBAL.TUNING.MUSHSPORE_MAX_DENSITY_RAD = 20
GLOBAL.TUNING.MUSHSPORE_DENSITY_CHECK_TIME = 15
GLOBAL.TUNING.MUSHSPORE_DENSITY_CHECK_VAR = 15

-- Strings
GLOBAL.STRINGS.NAMES.SPORE_TALL = "Blue Spore"
GLOBAL.STRINGS.NAMES.SPORE_MEDIUM = "Red Spore"  
GLOBAL.STRINGS.NAMES.SPORE_SMALL = "Green Spore"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPORE_TALL = "It's just drifting around."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPORE_MEDIUM = "Hasn't a care in the world."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPORE_SMALL = "That's a sight for spore eyes."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPORE_TALL = "How can a seed be so cheerful?"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPORE_MEDIUM = "Magical red, and yet it holds no power of use to me."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPORE_SMALL = "Hateful, ambulatory whimsy."
GLOBAL.STRINGS.CHARACTERS.WALANI.DESCRIBE.SPORE_TALL = "Is this a kind of pollen?"
GLOBAL.STRINGS.CHARACTERS.WALANI.DESCRIBE.SPORE_MEDIUM = "Is this a kind of pollen?"
GLOBAL.STRINGS.CHARACTERS.WALANI.DESCRIBE.SPORE_SMALL = "Is this a kind of pollen?"
GLOBAL.STRINGS.CHARACTERS.WARLY.DESCRIBE.SPORE_TALL = "You look delicious!"
GLOBAL.STRINGS.CHARACTERS.WARLY.DESCRIBE.SPORE_MEDIUM = "That's a new kind of spice?"
GLOBAL.STRINGS.CHARACTERS.WARLY.DESCRIBE.SPORE_SMALL = "Maybe i can cook this flying thing?"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPORE_TALL = "At peace, benevolent river spirit."
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPORE_MEDIUM = "At peace, benevolent flame spirit."
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPORE_SMALL = "At peace, benevolent forest spirit."
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPORE_TALL = "Blue! That's our favorite color!"
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPORE_MEDIUM = "Our favorite color! Red!"
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPORE_SMALL = "That's green, our favoritest color!"
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.SPORE_TALL = "Be free, little one!"
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.SPORE_MEDIUM = "Its life is short, but beautiful."
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.SPORE_SMALL = "It has no concept of time, or loss."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPORE_TALL = "A soft blue carrier of genetic information."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPORE_MEDIUM = "A bright red carrier of genetic information."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPORE_SMALL = "A lovely green carrier of genetic information."
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPORE_TALL = "It's like colorful sparks!"
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPORE_MEDIUM = "It's like floating fire!"
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPORE_SMALL = "It has no idea where it's going."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPORE_TALL = "Little blue bug has no wings."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPORE_MEDIUM = "Is tiny red bug?"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPORE_SMALL = "Nice green bug. Wolfgang will not swat."
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPORE_TALL = "A flying green pinecone!"
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPORE_MEDIUM = "A floating red pinecone!"
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPORE_SMALL = "We've been visited by a forest sprite, Lucy!"
GLOBAL.STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.SPORE_TALL = "Blue, like sea!"
GLOBAL.STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.SPORE_MEDIUM = "Are you coming from the volcano?"
GLOBAL.STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.SPORE_SMALL = "Oh please don't grow on my legs!"
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.SPORE_TALL = "DOES IT RUN ON BATTERIES?"
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.SPORE_MEDIUM = "BIOLOGICAL AIR POLLUTION"
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.SPORE_SMALL = "ORGANICS CAN'T KEEP THEIR BIOMATTER TO THEMSELVES"

-- Prefabs
table.insert(PrefabFiles, "mushtree_spores")