local cpy = TUNING.ROWBOAT_PERISHTIME

if TUNING.ROWBOAT_PERISHTIME * GetModConfigData("ROWBOAT_PERISHTIME") > cpy then
	TUNING.ROWBOAT_SPEED = 40
end

TUNING.ROWBOAT_PERISHTIME = TUNING.ROWBOAT_PERISHTIME * GetModConfigData("ROWBOAT_PERISHTIME")
TUNING.RAFT_PERISHTIME = TUNING.RAFT_PERISHTIME * GetModConfigData("RAFT_PERISHTIME")
TUNING.LOGRAFT_PERISHTIME = TUNING.LOGRAFT_PERISHTIME * GetModConfigData("LOGRAFT_PERISHTIME")
TUNING.CARGOBOAT_PERISHTIME = TUNING.CARGOBOAT_PERISHTIME * GetModConfigData("CARGOBOAT_PERISHTIME")
TUNING.ARMOUREDBOAT_PERISHTIME = TUNING.ARMOUREDBOAT_PERISHTIME * GetModConfigData("ARMOUREDBOAT_PERISHTIME")

TUNING.BOAT_TORCH_LIGHTTIME = TUNING.BOAT_TORCH_LIGHTTIME * GetModConfigData("BOAT_TORCH_LIGHTTIME")
TUNING.BOAT_LANTERN_LIGHTTIME = TUNING.BOAT_LANTERN_LIGHTTIME * GetModConfigData("BOAT_LANTERN_LIGHTTIME")
TUNING.BOTTLE_LANTERN_LIGHTTIME = TUNING.BOTTLE_LANTERN_LIGHTTIME * GetModConfigData("BOTTLE_LANTERN_LIGHTTIME")

TUNING.SAIL_PERISH_TIME = TUNING.SAIL_PERISH_TIME * GetModConfigData("SAIL_PERISH_TIME")
TUNING.CLOTH_SAIL_PERISH_TIME = TUNING.CLOTH_SAIL_PERISH_TIME * GetModConfigData("CLOTH_SAIL_PERISH_TIME")
TUNING.SNAKESKIN_SAIL_PERISH_TIME = TUNING.SNAKESKIN_SAIL_PERISH_TIME * GetModConfigData("SNAKESKIN_SAIL_PERISH_TIME")
TUNING.FEATHER_SAIL_PERISH_TIME = TUNING.FEATHER_SAIL_PERISH_TIME * GetModConfigData("FEATHER_SAIL_PERISH_TIME")
TUNING.IRON_WIND_PERISH_TIME = TUNING.IRON_WIND_PERISH_TIME * GetModConfigData("IRON_WIND_PERISH_TIME")