TUNING.HAMMER_LOOT_PERCENT = GetModConfigData("HAMMER_LOOT_PERCENT")
TUNING.AXE_USES = GetModConfigData("AXE_USES")
TUNING.HAMMER_USES = GetModConfigData("HAMMER_USES")
TUNING.SHOVEL_USES = GetModConfigData("SHOVEL_USES")
TUNING.PITCHFORK_USES = GetModConfigData("PITCHFORK_USES")
TUNING.PICKAXE_USES = GetModConfigData("PICKAXE_USES")
TUNING.BUGNET_USES = GetModConfigData("BUGNET_USES")
TUNING.FISHINGROD_USES = GetModConfigData("FISHINGROD_USES")
TUNING.MULTITOOL_AXE_PICKAXE_USES = GetModConfigData("MULTITOOL_AXE_PICKAXE_USES")

TUNING.SPEAR_USES = GetModConfigData("SPEAR_USES")
TUNING.SPIKE_USES = GetModConfigData("SPIKE_USES")
TUNING.BOOMERANG_USES = GetModConfigData("BOOMERANG_USES")
TUNING.NIGHTSWORD_USES = GetModConfigData("NIGHTSWORD_USES")
TUNING.HAMBAT_USES = GetModConfigData("HAMBAT_USES")
TUNING.BATBAT_USES = GetModConfigData("BATBAT_USES")
TUNING.RUINS_BAT_USES = GetModConfigData("RUINS_BAT_USES")

if TUNING.WATHGRITHR_SPEAR_USES ~= nil then
	TUNING.WATHGRITHR_SPEAR_USES = GetModConfigData("WATHGRITHR_SPEAR_USES")
end

if TUNING.MACHETE_USES ~= nil then
	TUNING.AXTINGUISHER_USES = GetModConfigData("AXTINGUISHER_USES")
	TUNING.FLAREGUN_USES = GetModConfigData("FLAREGUN_USES")
	TUNING.CUTLASS_USES = GetModConfigData("CUTLASS_USES")
	TUNING.PEG_LEG_USES = GetModConfigData("PEG_LEG_USES")
	TUNING.HARPOON_USES = GetModConfigData("HARPOON_USES")
	TUNING.MACHETE_USES = GetModConfigData("MACHETE_USES")
	TUNING.SPEAR_LAUNCHER_USES = GetModConfigData("SPEAR_LAUNCHER_USES")
end