TUNING.MINERHAT_LIGHTTIME = TUNING.MINERHAT_LIGHTTIME * GetModConfigData("MINERHAT_LIGHTTIME")
TUNING.LANTERN_LIGHTTIME = TUNING.LANTERN_LIGHTTIME * GetModConfigData("LANTERN_LIGHTTIME")
TUNING.SPIDERHAT_PERISHTIME = TUNING.SPIDERHAT_PERISHTIME * GetModConfigData("SPIDERHAT_PERISHTIME")
TUNING.ONEMANBAND_PERISHTIME = TUNING.ONEMANBAND_PERISHTIME * GetModConfigData("ONEMANBAND_PERISHTIME")
TUNING.UMBRELLA_PERISHTIME = TUNING.UMBRELLA_PERISHTIME * GetModConfigData("UMBRELLA_PERISHTIME")
TUNING.EARMUFF_PERISHTIME = TUNING.EARMUFF_PERISHTIME * GetModConfigData("EARMUFF_PERISHTIME")
TUNING.WINTERHAT_PERISHTIME = TUNING.WINTERHAT_PERISHTIME * GetModConfigData("WINTERHAT_PERISHTIME")
TUNING.BEEFALOHAT_PERISHTIME = TUNING.BEEFALOHAT_PERISHTIME * GetModConfigData("BEEFALOHAT_PERISHTIME")
TUNING.TRUNKVEST_PERISHTIME = TUNING.TRUNKVEST_PERISHTIME * GetModConfigData("TRUNKVEST_PERISHTIME")
TUNING.SWEATERVEST_PERISHTIME = TUNING.SWEATERVEST_PERISHTIME * GetModConfigData("SWEATERVEST_PERISHTIME")
TUNING.HUNGERBELT_PERISHTIME = TUNING.HUNGERBELT_PERISHTIME * GetModConfigData("HUNGERBELT_PERISHTIME")
TUNING.WALRUSHAT_PERISHTIME = TUNING.WALRUSHAT_PERISHTIME * GetModConfigData("WALRUSHAT_PERISHTIME")
TUNING.FEATHERHAT_PERISHTIME = TUNING.FEATHERHAT_PERISHTIME * GetModConfigData("FEATHERHAT_PERISHTIME")
TUNING.TOPHAT_PERISHTIME = TUNING.TOPHAT_PERISHTIME * GetModConfigData("TOPHAT_PERISHTIME")

if not TUNING.STRAWHAT_PERISHTIME == nil then
	TUNING.STRAWHAT_PERISHTIME = TUNING.STRAWHAT_PERISHTIME * GetModConfigData("STRAWHAT_PERISHTIME")
end

if not TUNING.ICEHAT_PERISHTIME == nil then
	TUNING.GRASS_UMBRELLA_PERISHTIME = TUNING.GRASS_UMBRELLA_PERISHTIME * GetModConfigData("GRASS_UMBRELLA_PERISHTIME")
	TUNING.ICEHAT_PERISHTIME = TUNING.ICEHAT_PERISHTIME * GetModConfigData("ICEHAT_PERISHTIME")
	TUNING.REFLECTIVEVEST_PERISHTIME = TUNING.REFLECTIVEVEST_PERISHTIME * GetModConfigData("REFLECTIVEVEST_PERISHTIME")
	TUNING.HAWAIIANSHIRT_PERISHTIME = TUNING.HAWAIIANSHIRT_PERISHTIME * GetModConfigData("HAWAIIANSHIRT_PERISHTIME")
	TUNING.CATCOONHAT_PERISHTIME = TUNING.CATCOONHAT_PERISHTIME * GetModConfigData("CATCOONHAT_PERISHTIME")
	TUNING.RAINHAT_PERISHTIME = TUNING.RAINHAT_PERISHTIME * GetModConfigData("RAINHAT_PERISHTIME")
	TUNING.RAINCOAT_PERISHTIME = TUNING.RAINCOAT_PERISHTIME * GetModConfigData("RAINCOAT_PERISHTIME")
	TUNING.BEARGERVEST_PERISHTIME = TUNING.BEARGERVEST_PERISHTIME * GetModConfigData("BEARGERVEST_PERISHTIME")
	TUNING.EYEBRELLA_PERISHTIME = TUNING.EYEBRELLA_PERISHTIME * GetModConfigData("EYEBRELLA_PERISHTIME")
	TUNING.MOLEHAT_PERISHTIME = TUNING.MOLEHAT_PERISHTIME * GetModConfigData("MOLEHAT_PERISHTIME")
end

if not TUNING.SNAKESKINHAT_PERISHTIME == nil then
	TUNING.SNAKESKINHAT_PERISHTIME = TUNING.SNAKESKINHAT_PERISHTIME * GetModConfigData("SNAKESKINHAT_PERISHTIME")
	TUNING.ARMOR_SNAKESKIN_PERISHTIME = TUNING.ARMOR_SNAKESKIN_PERISHTIME * GetModConfigData("ARMOR_SNAKESKIN_PERISHTIME")
	TUNING.BLUBBERSUIT_PERISHTIME = TUNING.BLUBBERSUIT_PERISHTIME * GetModConfigData("BLUBBERSUIT_PERISHTIME")
	TUNING.WINDBREAKER_PERISHTIME = TUNING.WINDBREAKER_PERISHTIME * GetModConfigData("WINDBREAKER_PERISHTIME")
	TUNING.GASHAT_PERISHTIME = TUNING.GASHAT_PERISHTIME * GetModConfigData("GASHAT_PERISHTIME")
	TUNING.AERODYNAMICHAT_PERISHTIME = TUNING.AERODYNAMICHAT_PERISHTIME * GetModConfigData("AERODYNAMICHAT_PERISHTIME")
	TUNING.CAPTAINHAT_PERISHTIME = TUNING.CAPTAINHAT_PERISHTIME * GetModConfigData("CAPTAINHAT_PERISHTIME")
	TUNING.PIRATEHAT_PERISHTIME = TUNING.PIRATEHAT_PERISHTIME * GetModConfigData("PIRATEHAT_PERISHTIME")
	TUNING.SHARK_HAT_PERISHTIME = TUNING.SHARK_HAT_PERISHTIME * GetModConfigData("SHARK_HAT_PERISHTIME")
	TUNING.DOUBLE_UMBRELLA_PERISHTIME = TUNING.DOUBLE_UMBRELLA_PERISHTIME * GetModConfigData("DOUBLE_UMBRELLA_PERISHTIME")
	TUNING.SHARK_HAT_PERISHTIME = TUNING.SHARK_HAT_PERISHTIME * GetModConfigData("SHARK_HAT_PERISHTIME")
	TUNING.TARSUIT_PERISHTIME = TUNING.TARSUIT_PERISHTIME * GetModConfigData("TARSUIT_PERISHTIME")
	TUNING.WOODLEGSHAT_PERISHTIME = TUNING.WOODLEGSHAT_PERISHTIME * GetModConfigData("WOODLEGSHAT_PERISHTIME")
end