TUNING.PANFLUTE_USES = GetModConfigData("PANFLUTE_USES")
TUNING.HORN_USES = GetModConfigData("HORN_USES")
TUNING.TRAP_TEETH_USES = GetModConfigData("TRAP_TEETH_USES")
TUNING.TRAP_USES = GetModConfigData("TRAP_USES")
TUNING.TENT_USES = GetModConfigData("TENT_USES")
TUNING.UMBRELLA_USES = GetModConfigData("UMBRELLA_USES")
TUNING.SEWINGKIT_USES = GetModConfigData("SEWINGKIT_USES")
TUNING.TORCH_FUEL = TUNING.TORCH_FUEL * GetModConfigData("TORCH_FUEL")

if not TUNING.SIESTA_CANOPY_USES == nil then
	TUNING.SIESTA_CANOPY_USES = GetModConfigData("SIESTA_CANOPY_USES")
	TUNING.FERTILIZER_USES = GetModConfigData("FERTILIZER_USES")
	TUNING.GLOMMERBELL_USES = GetModConfigData("GLOMMERBELL_USES")
	TUNING.FEATHER_FAN_USES = GetModConfigData("FEATHER_FAN_USES")
end

if not TUNING.MONKEYBALL_USES == nil then
	TUNING.MONKEYBALL_USES = GetModConfigData("MONKEYBALL_USES")
	TUNING.TELESCOPE_USES = GetModConfigData("TELESCOPE_USES")
	TUNING.BOAT_REPAIR_KIT_USES = GetModConfigData("BOAT_REPAIR_KIT_USES")
end